apiVersion:  v1
kind: Pod
metadata:
  name: shared-gpu1
spec:
  containers:
  - name: shared-gpu1
    image: tkanng/ubuntu:hhh
    command: 
    resources:
      limits:
        nvidia.com/shared-gpu: "1"
